/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Átila Becker (https://sketchfab.com/atilabecker)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lightsaber-1e95a8ccbbfe4732891eb76a683e9c29
title: Lightsaber
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LightSaber(props) {
    const { nodes, materials } = useGLTF("/lightsaber.glb");
    return (
        <group {...props} dispose={null}>
            <group
                position={[0.59, -0.34, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.01}
            >
                <group position={[-3.02, -3.02, -15.88]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_3.geometry}
                        material={materials.lambert2SG}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/lightsaber.glb");