/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Heniqueish (https://sketchfab.com/Heniqueish)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/elder-wand-37cee9fb76494799b743aea2fe41fd26
title: Elder Wand
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MagicWand(props) {
    const { nodes, materials } = useGLTF("/elder_wand.glb");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial.geometry}
                        material={materials.ElderWand}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/elder_wand.glb");